In [50]:
import pandas as pd

In [66]:
ORCL=pd.read_csv('/users/neiloza/Desktop/Capstone_1_Stocks/ORCL.csv',sep=',', index_col='Date', parse_dates=True)
ORCL['Name']='ORCL'
ORCL=ORCL.reset_index()
ORCL=ORCL.set_index(['Name','Date'])
complete_stock_list=ORCL

In [67]:
def add_new_stock(filename):
    df=pd.read_csv(filename, sep=',', index_col='Date', parse_dates=True)
    period_index=filename.find('.')
    last_slash=filename.rfind('/')
    stock_name=filename[last_slash+1:period_index]
    df['Name']=stock_name
    df=df.reset_index()
    df=df.set_index(['Name','Date'])
    global complete_stock_list
    complete_stock_list=complete_stock_list.append(df)

In [68]:
add_new_stock('/users/neiloza/Desktop/Capstone_1_Stocks/LEG.csv')
add_new_stock('/users/neiloza/Desktop/Capstone_1_Stocks/DRI.csv')
complete_stock_list

                       Open        High         Low       Close   Adj Close  \
Name Date
ORCL 2000-01-03   31.156250   31.296875   27.906250   29.531250   26.164173
     2000-01-04   28.875000   29.656250   26.250000   26.921875   23.852308
     2000-01-05   25.406250   26.593750   24.000000   25.500000   22.592552
     2000-01-06   25.039049   26.250000   23.671875   24.000000   21.263577
     2000-01-07   23.750000   25.875000   23.390625   25.843750   22.897104
     2000-01-10   27.000000   29.000000   26.375000   28.937500   25.638119
     2000-01-11   28.156250   28.687500   27.375000   28.093750   24.890572
     2000-01-12   28.062500   28.062500   25.921875   26.406250   23.395473
     2000-01-13   27.125000   27.468750   25.875000   26.265625   23.270878
     2000-01-14   27.250000   27.843750   26.187500   26.703125   23.658499
     2000-01-18   26.968750   28.625000   26.406250   27.812500   24.641380
     2000-01-19   28.062500   29.125000   27.000000   28.562500   25.305872
     2000-01-20   29.500000   30.125000   29.062500   29.625000   26.247229
     2000-01-21   30.750000   30.750000   29.500000   29.843750   26.441036
     2000-01-24   30.125000   30.187500   27.000000   27.093750   24.004585
     2000-01-25   27.531250   28.750000   27.437500   28.218750   25.001318
     2000-01-26   28.375000   29.468750   27.500000   27.531250   24.392202
     2000-01-27   27.906250   28.343750   25.000000   25.906250   22.952480
     2000-01-28   25.750000   25.968750   23.312500   23.687500   20.986710
     2000-01-31   23.968750   25.062500   23.531250   24.976549   22.128780
     2000-02-01   25.625000   27.156250   25.000000   27.000000   23.921524
     2000-02-02   27.468750   28.000000   27.000000   27.156250   24.059961
     2000-02-03   27.687500   28.500000   27.125000   28.343750   25.112074
     2000-02-04   28.812500   29.125000   28.406250   28.906250   25.610428
     2000-02-07   29.656250   30.000000   29.437500   29.968750   26.551788
     2000-02-08   30.375000   30.718750   29.500000   29.781250   26.385668
     2000-02-09   30.031250   30.656250   29.406250   29.968750   26.551788
     2000-02-10   30.000000   31.312500   29.000000   31.156250   27.603889
     2000-02-11   31.250000   32.375000   29.375000   29.843750   26.441036
     2000-02-14   30.437500   31.125000   29.312500   31.093750   27.548519
...                     ...         ...         ...         ...         ...
LEG  2019-01-10   37.910000   38.410000   37.639999   38.310001   38.310001
     2019-01-11   38.279999   38.360001   37.820000   38.340000   38.340000
     2019-01-14   38.189999   38.570000   38.029999   38.320000   38.320000
     2019-01-15   38.349998   38.500000   37.840000   38.430000   38.430000
     2019-01-16   38.540001   38.950001   38.349998   38.400002   38.400002
     2019-01-17   38.270000   39.049999   38.250000   38.869999   38.869999
     2019-01-18   39.230000   39.959999   39.090000   39.610001   39.610001
     2019-01-22   39.439999   39.470001   38.799999   39.090000   39.090000
     2019-01-23   39.180000   39.400002   38.349998   38.820000   38.820000
DRI  2018-12-24   98.699997   98.699997   95.919998   96.709999   96.023270
     2018-12-26   97.029999   98.580002   96.410004   98.570000   97.870064
     2018-12-27   97.820000   98.550003   95.830002   98.550003   97.850204
     2018-12-28   98.750000   99.900002   97.940002   98.339996   97.641693
     2018-12-31   98.570000   99.860001   97.980003   99.860001   99.150902
     2019-01-02   99.260002  100.110001   98.230003   99.930000   99.220406
     2019-01-03   99.099998   99.680000   97.910004   98.320000   97.621834
     2019-01-04   99.379997  101.690002   98.889999  101.400002  100.679970
     2019-01-07  101.739998  104.889999  101.629997  103.940002  103.201927
     2019-01-08  104.510002  105.989998  103.730003  105.620003  104.870003
     2019-01-09  105.540001  105.800003  104.180000  104.870003  104.870003
     2019-01-10  104.809998  105.879997  104.099998  105.779999  105.779999
     2019-01-11  106.419998  108.199997  106.419998  107.989998  107.989998
     2019-01-14  107.650002  107.879997  105.339996  105.919998  105.919998
     2019-01-15  106.440002  107.510002  105.480003  107.260002  107.260002
     2019-01-16  107.610001  107.860001  105.860001  106.790001  106.790001
     2019-01-17  106.820000  108.430000  106.820000  108.010002  108.010002
     2019-01-18  108.660004  109.199997  107.559998  109.019997  109.019997
     2019-01-22  108.699997  110.080002  107.580002  108.629997  108.629997
     2019-01-23  109.250000  109.250000  107.080002  108.089996  108.089996
     2019-01-24  108.349998  108.809998  107.480003  107.912598  107.912598

                    Volume
Name Date
ORCL 2000-01-03   98114800
     2000-01-04  116824800
     2000-01-05  166054000
     2000-01-06  109880000
     2000-01-07   91755600
     2000-01-10   91518000
     2000-01-11   86585200
     2000-01-12   83443600
     2000-01-13   55779200
     2000-01-14   57078000
     2000-01-18   66780000
     2000-01-19   49198400
     2000-01-20   54526800
     2000-01-21   50891000
     2000-01-24   50022400
     2000-01-25   53059200
     2000-01-26   47569200
     2000-01-27   61054000
     2000-01-28   86394000
     2000-01-31   68148000
     2000-02-01   57105600
     2000-02-02   63933000
     2000-02-03   55533200
     2000-02-04   40916000
     2000-02-07   44691200
     2000-02-08   55718000
     2000-02-09   52471600
     2000-02-10   45288600
     2000-02-11   55774000
     2000-02-14   37599800
...                    ...
LEG  2019-01-10    1092600
     2019-01-11     914000
     2019-01-14     581100
     2019-01-15     730300
     2019-01-16     981800
     2019-01-17     590500
     2019-01-18    1013600
     2019-01-22     952000
     2019-01-23     886400
DRI  2018-12-24     907100
     2018-12-26    1172400
     2018-12-27    1372900
     2018-12-28    1290400
     2018-12-31    1163400
     2019-01-02    1563600
     2019-01-03    1857800
     2019-01-04    2070100
     2019-01-07    1889300
     2019-01-08    1676700
     2019-01-09    1105600
     2019-01-10     996200
     2019-01-11    1340700
     2019-01-14    1493700
     2019-01-15     955300
     2019-01-16    1090600
     2019-01-17    1116400
     2019-01-18    1111200
     2019-01-22    1146000
     2019-01-23    1099900
     2019-01-24     324354

[9609 rows x 6 columns]

In [39]:
DRI=pd.read_csv('/users/neiloza/Desktop/Capstone_1_Stocks/DRI.csv',sep=',', index_col='Date', parse_dates=True)
DRI['Name']='DRI'
DRI=DRI.reset_index()
DRI=DRI.set_index(['Name','Date'])

In [36]:
LEG=pd.read_csv('/users/neiloza/Desktop/Capstone_1_Stocks/LEG.csv',sep=',', index_col='Date', parse_dates=True)
LEG['Name']='LEG'
LEG=LEG.reset_index()
LEG=LEG.set_index(['Name','Date'])

In [32]:
file='/users/neiloza/Desktop/Capstone_1_Stocks/LEG.csv'
period_index=file.find('.')
print(period_index)
last_slash=file.rfind('/')
print(last_slash)
stock_name=file[last_slash+1:period_index]

44
40
LEG

In [35]:
total=LEG.append(DRI)
total

                       Open        High         Low       Close   Adj Close  \
Name Date
LEG  2000-01-03   21.250000   21.375000   20.062500   20.562500   10.575291
     2000-01-04   20.312500   20.312500   19.437500   19.500000   10.028845
     2000-01-05   19.625000   19.750000   19.000000   19.500000   10.028845
     2000-01-06   19.312500   19.625000   19.062500   19.437500    9.996701
     2000-01-07   19.500000   19.750000   19.062500   19.750000   10.157419
     2000-01-10   19.875000   19.937500   19.062500   19.687500   10.125280
     2000-01-11   19.500000   20.187500   19.500000   19.812500   10.189564
     2000-01-12   19.812500   19.875000   19.187500   19.187500    9.868121
     2000-01-13   19.187500   19.250000   18.687500   19.187500    9.868121
     2000-01-14   19.250000   19.437500   18.875000   19.312500    9.932416
     2000-01-18   19.125000   19.312500   18.937500   19.312500    9.932416
     2000-01-19   19.250000   19.312500   18.937500   19.000000    9.771695
     2000-01-20   18.937500   19.062500   18.375000   18.500000    9.514548
     2000-01-21   19.000000   19.125000   18.500000   19.062500    9.803835
     2000-01-24   19.125000   19.312500   18.500000   18.687500    9.610976
     2000-01-25   18.562500   18.687500   17.812500   18.062500    9.289540
     2000-01-26   18.250000   18.437500   17.625000   18.187500    9.353828
     2000-01-27   18.000000   18.562500   17.750000   18.125000    9.321682
     2000-01-28   18.125000   18.250000   17.750000   17.937500    9.225248
     2000-01-31   17.812500   18.000000   17.562500   18.000000    9.257398
     2000-02-01   17.875000   18.500000   17.375000   18.250000    9.385968
     2000-02-02   18.000000   18.000000   17.562500   17.687500    9.096676
     2000-02-03   17.750000   18.500000   17.687500   18.187500    9.353828
     2000-02-04   17.937500   18.375000   17.562500   17.625000    9.064535
     2000-02-07   17.562500   17.625000   17.000000   17.312500    8.903811
     2000-02-08   17.562500   17.750000   17.250000   17.500000    9.000243
     2000-02-09   17.250000   18.000000   17.062500   17.312500    8.903811
     2000-02-10   17.437500   17.437500   16.937500   17.062500    8.775238
     2000-02-11   16.937500   17.250000   16.687500   16.750000    8.614521
     2000-02-14   17.000000   17.312500   16.687500   16.750000    8.614521
...                     ...         ...         ...         ...         ...
     2019-01-10   37.910000   38.410000   37.639999   38.310001   38.310001
     2019-01-11   38.279999   38.360001   37.820000   38.340000   38.340000
     2019-01-14   38.189999   38.570000   38.029999   38.320000   38.320000
     2019-01-15   38.349998   38.500000   37.840000   38.430000   38.430000
     2019-01-16   38.540001   38.950001   38.349998   38.400002   38.400002
     2019-01-17   38.270000   39.049999   38.250000   38.869999   38.869999
     2019-01-18   39.230000   39.959999   39.090000   39.610001   39.610001
     2019-01-22   39.439999   39.470001   38.799999   39.090000   39.090000
     2019-01-23   39.180000   39.400002   38.349998   38.820000   38.820000
DRI  2018-12-24   98.699997   98.699997   95.919998   96.709999   96.023270
     2018-12-26   97.029999   98.580002   96.410004   98.570000   97.870064
     2018-12-27   97.820000   98.550003   95.830002   98.550003   97.850204
     2018-12-28   98.750000   99.900002   97.940002   98.339996   97.641693
     2018-12-31   98.570000   99.860001   97.980003   99.860001   99.150902
     2019-01-02   99.260002  100.110001   98.230003   99.930000   99.220406
     2019-01-03   99.099998   99.680000   97.910004   98.320000   97.621834
     2019-01-04   99.379997  101.690002   98.889999  101.400002  100.679970
     2019-01-07  101.739998  104.889999  101.629997  103.940002  103.201927
     2019-01-08  104.510002  105.989998  103.730003  105.620003  104.870003
     2019-01-09  105.540001  105.800003  104.180000  104.870003  104.870003
     2019-01-10  104.809998  105.879997  104.099998  105.779999  105.779999
     2019-01-11  106.419998  108.199997  106.419998  107.989998  107.989998
     2019-01-14  107.650002  107.879997  105.339996  105.919998  105.919998
     2019-01-15  106.440002  107.510002  105.480003  107.260002  107.260002
     2019-01-16  107.610001  107.860001  105.860001  106.790001  106.790001
     2019-01-17  106.820000  108.430000  106.820000  108.010002  108.010002
     2019-01-18  108.660004  109.199997  107.559998  109.019997  109.019997
     2019-01-22  108.699997  110.080002  107.580002  108.629997  108.629997
     2019-01-23  109.250000  109.250000  107.080002  108.089996  108.089996
     2019-01-24  108.349998  108.809998  107.480003  107.912598  107.912598

                  Volume
Name Date
LEG  2000-01-03   361300
     2000-01-04   560900
     2000-01-05   870300
     2000-01-06   776400
     2000-01-07   485400
     2000-01-10   435400
     2000-01-11   402200
     2000-01-12   421100
     2000-01-13   472200
     2000-01-14   341500
     2000-01-18   368600
     2000-01-19   332300
     2000-01-20   494300
     2000-01-21   661100
     2000-01-24   293400
     2000-01-25   467600
     2000-01-26   528700
     2000-01-27   358100
     2000-01-28   355600
     2000-01-31   498000
     2000-02-01   699600
     2000-02-02   467900
     2000-02-03   595600
     2000-02-04   582900
     2000-02-07   520400
     2000-02-08   304400
     2000-02-09   548700
     2000-02-10   431800
     2000-02-11   384500
     2000-02-14   461900
...                  ...
     2019-01-10  1092600
     2019-01-11   914000
     2019-01-14   581100
     2019-01-15   730300
     2019-01-16   981800
     2019-01-17   590500
     2019-01-18  1013600
     2019-01-22   952000
     2019-01-23   886400
DRI  2018-12-24   907100
     2018-12-26  1172400
     2018-12-27  1372900
     2018-12-28  1290400
     2018-12-31  1163400
     2019-01-02  1563600
     2019-01-03  1857800
     2019-01-04  2070100
     2019-01-07  1889300
     2019-01-08  1676700
     2019-01-09  1105600
     2019-01-10   996200
     2019-01-11  1340700
     2019-01-14  1493700
     2019-01-15   955300
     2019-01-16  1090600
     2019-01-17  1116400
     2019-01-18  1111200
     2019-01-22  1146000
     2019-01-23  1099900
     2019-01-24   324354

[4815 rows x 6 columns]

In [47]:
sample1=add_new_stock('/users/neiloza/Desktop/Capstone_1_Stocks/LEG.csv')
sample1

                      Open       High        Low      Close  Adj Close  \
Name Date
LEG  2000-01-03  21.250000  21.375000  20.062500  20.562500  10.575291
     2000-01-04  20.312500  20.312500  19.437500  19.500000  10.028845
     2000-01-05  19.625000  19.750000  19.000000  19.500000  10.028845
     2000-01-06  19.312500  19.625000  19.062500  19.437500   9.996701
     2000-01-07  19.500000  19.750000  19.062500  19.750000  10.157419
     2000-01-10  19.875000  19.937500  19.062500  19.687500  10.125280
     2000-01-11  19.500000  20.187500  19.500000  19.812500  10.189564
     2000-01-12  19.812500  19.875000  19.187500  19.187500   9.868121
     2000-01-13  19.187500  19.250000  18.687500  19.187500   9.868121
     2000-01-14  19.250000  19.437500  18.875000  19.312500   9.932416
     2000-01-18  19.125000  19.312500  18.937500  19.312500   9.932416
     2000-01-19  19.250000  19.312500  18.937500  19.000000   9.771695
     2000-01-20  18.937500  19.062500  18.375000  18.500000   9.514548
     2000-01-21  19.000000  19.125000  18.500000  19.062500   9.803835
     2000-01-24  19.125000  19.312500  18.500000  18.687500   9.610976
     2000-01-25  18.562500  18.687500  17.812500  18.062500   9.289540
     2000-01-26  18.250000  18.437500  17.625000  18.187500   9.353828
     2000-01-27  18.000000  18.562500  17.750000  18.125000   9.321682
     2000-01-28  18.125000  18.250000  17.750000  17.937500   9.225248
     2000-01-31  17.812500  18.000000  17.562500  18.000000   9.257398
     2000-02-01  17.875000  18.500000  17.375000  18.250000   9.385968
     2000-02-02  18.000000  18.000000  17.562500  17.687500   9.096676
     2000-02-03  17.750000  18.500000  17.687500  18.187500   9.353828
     2000-02-04  17.937500  18.375000  17.562500  17.625000   9.064535
     2000-02-07  17.562500  17.625000  17.000000  17.312500   8.903811
     2000-02-08  17.562500  17.750000  17.250000  17.500000   9.000243
     2000-02-09  17.250000  18.000000  17.062500  17.312500   8.903811
     2000-02-10  17.437500  17.437500  16.937500  17.062500   8.775238
     2000-02-11  16.937500  17.250000  16.687500  16.750000   8.614521
     2000-02-14  17.000000  17.312500  16.687500  16.750000   8.614521
...                    ...        ...        ...        ...        ...
     2018-12-10  38.369999  38.570000  37.279999  37.700001  37.318481
     2018-12-11  38.320000  38.570000  37.400002  37.560001  37.179901
     2018-12-12  37.959999  38.169998  37.540001  37.549999  37.169998
     2018-12-13  37.389999  37.580002  36.619999  36.639999  36.639999
     2018-12-14  36.230000  37.000000  35.980000  36.160000  36.160000
     2018-12-17  35.990002  37.349998  35.939999  36.330002  36.330002
     2018-12-18  36.560001  37.340000  36.180000  36.490002  36.490002
     2018-12-19  36.570000  37.389999  35.779999  35.840000  35.840000
     2018-12-20  35.740002  36.520000  35.639999  36.200001  36.200001
     2018-12-21  36.389999  37.070000  34.880001  34.880001  34.880001
     2018-12-24  34.700001  35.020000  33.939999  33.970001  33.970001
     2018-12-26  34.259998  35.389999  33.480000  35.380001  35.380001
     2018-12-27  34.900002  36.049999  34.549999  36.049999  36.049999
     2018-12-28  36.119999  36.380001  35.480000  35.810001  35.810001
     2018-12-31  35.910000  36.150002  35.340000  35.840000  35.840000
     2019-01-02  35.369999  36.279999  35.110001  36.009998  36.009998
     2019-01-03  35.759998  35.959999  34.950001  35.450001  35.450001
     2019-01-04  35.880001  36.759998  35.880001  36.520000  36.520000
     2019-01-07  36.680000  37.619999  36.330002  37.160000  37.160000
     2019-01-08  37.599998  37.880001  37.130001  37.689999  37.689999
     2019-01-09  37.779999  38.220001  37.509998  37.900002  37.900002
     2019-01-10  37.910000  38.410000  37.639999  38.310001  38.310001
     2019-01-11  38.279999  38.360001  37.820000  38.340000  38.340000
     2019-01-14  38.189999  38.570000  38.029999  38.320000  38.320000
     2019-01-15  38.349998  38.500000  37.840000  38.430000  38.430000
     2019-01-16  38.540001  38.950001  38.349998  38.400002  38.400002
     2019-01-17  38.270000  39.049999  38.250000  38.869999  38.869999
     2019-01-18  39.230000  39.959999  39.090000  39.610001  39.610001
     2019-01-22  39.439999  39.470001  38.799999  39.090000  39.090000
     2019-01-23  39.180000  39.400002  38.349998  38.820000  38.820000

                  Volume
Name Date
LEG  2000-01-03   361300
     2000-01-04   560900
     2000-01-05   870300
     2000-01-06   776400
     2000-01-07   485400
     2000-01-10   435400
     2000-01-11   402200
     2000-01-12   421100
     2000-01-13   472200
     2000-01-14   341500
     2000-01-18   368600
     2000-01-19   332300
     2000-01-20   494300
     2000-01-21   661100
     2000-01-24   293400
     2000-01-25   467600
     2000-01-26   528700
     2000-01-27   358100
     2000-01-28   355600
     2000-01-31   498000
     2000-02-01   699600
     2000-02-02   467900
     2000-02-03   595600
     2000-02-04   582900
     2000-02-07   520400
     2000-02-08   304400
     2000-02-09   548700
     2000-02-10   431800
     2000-02-11   384500
     2000-02-14   461900
...                  ...
     2018-12-10  1621200
     2018-12-11   961000
     2018-12-12   904300
     2018-12-13   965700
     2018-12-14  2013500
     2018-12-17  2098700
     2018-12-18  1602400
     2018-12-19  1882700
     2018-12-20  1777300
     2018-12-21  4323700
     2018-12-24   659900
     2018-12-26  1124000
     2018-12-27  1539600
     2018-12-28  1162900
     2018-12-31   948900
     2019-01-02  1379700
     2019-01-03   843400
     2019-01-04   966200
     2019-01-07  1013000
     2019-01-08   929300
     2019-01-09  1548600
     2019-01-10  1092600
     2019-01-11   914000
     2019-01-14   581100
     2019-01-15   730300
     2019-01-16   981800
     2019-01-17   590500
     2019-01-18  1013600
     2019-01-22   952000
     2019-01-23   886400

[4794 rows x 6 columns]