In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

loan_data=pd.read_csv('/Users/neiloza/Downloads/lending-club-loan-data/loan.csv',low_memory=True)

/Users/neiloza/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
entries=len(loan_data.index)
percentile=.4
loan_data_cleaned=loan_data.dropna(thresh=int(percentile*entries),axis=1)
loan_data_cleaned=loan_data_cleaned[loan_data_cleaned.loan_status!='Fully Paid']
loan_data_cleaned

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,...,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,N,Cash,N
1,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,...,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,N,Cash,N
2,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,...,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,N,Cash,N
3,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,...,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,N,Cash,N
4,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,...,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,N,Cash,N
5,5550,5550,5550.0,36 months,15.02,192.45,C,C3,Director COE,10+ years,...,60.0,0.0,0.0,831687.0,185378.0,65900.0,203159.0,N,Cash,N
6,2000,2000,2000.0,36 months,17.97,72.28,D,D1,Account Manager,4 years,...,NaN,0.0,0.0,854.0,854.0,0.0,0.0,N,Cash,N
7,6000,6000,6000.0,36 months,13.56,203.79,C,C1,Assistant Director,10+ years,...,85.7,0.0,0.0,117242.0,91535.0,33100.0,61742.0,N,DirectPay,N
8,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Legal Assistant III,10+ years,...,60.0,0.0,0.0,57426.0,41882.0,21500.0,34626.0,N,Cash,N
9,6000,6000,6000.0,36 months,14.47,206.44,C,C2,NaN,< 1 year,...,26.3,0.0,0.0,477390.0,105911.0,98300.0,89600.0,N,Cash,N
10,5500,5500,5500.0,36 months,22.35,211.05,D,D5,NaN,< 1 year,...,100.0,0.0,0.0,243452.0,18185.0,4800.0,15649.0,N,Cash,N
11,28000,28000,28000.0,60 months,11.31,613.13,B,B3,Consultant,2 years,...,37.5,0.0,0.0,259435.0,65636.0,100400.0,17535.0,N,DirectPay,N
12,11200,11200,11200.0,36 months,8.19,351.95,A,A4,Job Coach Supervisor,10+ years,...,20.0,0.0,0.0,345654.0,78795.0,34900.0,114578.0,N,Cash,N
13,6500,6500,6500.0,36 months,17.97,234.90,D,D1,Quality Field Engineer,4 years,...,20.0,0.0,0.0,169160.0,116747.0,12300.0,129860.0,N,Cash,N
14,22000,22000,22000.0,60 months,12.98,500.35,B,B5,Teller,10+ years,...,0.0,0.0,0.0,71932.0,22337.0,27200.0,38535.0,N,Cash,N
15,3500,3500,3500.0,36 months,16.14,123.30,C,C4,respritory therapist,10+ years,...,50.0,0.0,0.0,42328.0,16085.0,8000.0,27028.0,N,Cash,N
16,7000,7000,7000.0,36 months,12.98,235.80,B,B5,Worship Director,4 years,...,0.0,0.0,0.0,214624.0,76709.0,7200.0,96826.0,N,Cash,N
17,25000,25000,25000.0,60 months,16.91,620.11,C,C5,Processor,10+ years,...,100.0,0.0,0.0,92334.0,3044.0,1000.0,0.0,N,Cash,N
18,16000,16000,16000.0,60 months,20.89,431.87,D,D4,Neonatal Nurse Practitioner,4 years,...,100.0,0.0,0.0,444217.0,266754.0,13500.0,239338.0,N,Cash,N
19,13000,13000,13000.0,60 months,14.47,305.67,C,C2,Stationary Engineer,10+ years,...,33.3,0.0,0.0,176598.0,50920.0,26700.0,50898.0,N,Cash,N
20,10000,10000,10000.0,36 months,13.56,339.65,C,C1,NaN,< 1 year,...,80.0,1.0,0.0,48052.0,45972.0,11500.0,34852.0,N,Cash,N
21,13000,13000,13000.0,36 months,14.47,447.29,C,C2,Exhibits director,10+ years,...,75.0,0.0,0.0,41150.0,13878.0,13900.0,1000.0,N,Cash,N
22,9600,9600,9600.0,36 months,23.40,373.62,E,E1,driver coordinator,9 years,...,85.7,0.0,0.0,68902.0,24165.0,7600.0,40402.0,N,Cash,N
23,3500,3500,3500.0,36 months,20.89,131.67,D,D4,gas attendant,10+ years,...,0.0,0.0,0.0,217000.0,26902.0,5000.0,25000.0,N,Cash,N
24,16000,16000,16000.0,60 months,26.31,481.99,E,E4,Financial Relationship Associate,< 1 year,...,55.6,0.0,0.0,45709.0,29869.0,13900.0,10809.0,N,Cash,N
25,15000,15000,14975.0,60 months,14.47,352.69,C,C2,NaN,NaN,...,50.0,0.0,0.0,118790.0,24507.0,9900.0,14490.0,N,Cash,N
26,13000,13000,13000.0,36 months,23.40,505.95,E,E1,Sale Representative,2 years,...,66.7,0.0,0.0,137276.0,87876.0,58600.0,74676.0,N,Cash,N
27,23000,23000,23000.0,60 months,20.89,620.81,D,D4,Operator,5 years,...,0.0,0.0,0.0,7500.0,976.0,3300.0,0.0,N,Cash,N
28,8000,8000,8000.0,36 months,23.40,311.35,E,E1,Manager,10+ years,...,100.0,1.0,0.0,199744.0,31078.0,2300.0,32206.0,N,Cash,N
29,32075,32075,32075.0,60 months,11.80,710.26,B,B4,Nursing Supervisor,10+ years,...,50.0,0.0,0.0,360433.0,56635.0,20000.0,80125.0,N,Cash,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260628,18000,18000,18000.0,36 months,24.85,714.25,E,E3,Inventory Control,2 years,...,66.7,0.0,0.0,38400.0,27558.0,24400.0,14000.0,N,Cash,N
2260629,12225,12225,12175.0,36 months,21.45,463.41,D,D5,Driver,10+ years,...,66.7,0.0,0.0,211061.0,26985.0,22150.0,13203.0,N,Cash,Y
2260630,5000,5000,5000.0,36 months,10.91,163.49,B,B4,NaN,NaN,...,33.3,0.0,0.0,39387.0,19328.0,10300.0,23787.0,N,Cash,N
2260631,25600,25600,25600.0,36 months,22.91,989.77,E,E1,Trainer,10+ years,...,60.0,0.0,2.0,64510.0,48017.0,19600.0,40210.0,N,Cash,N
2260633,30000,30000,29725.0,60 months,30.17,973.74,F,F3,Lead,10+ years,...,50.0,1.0,0.0,75082.0,54301.0,20800.0,49382.0,N,Cash,N
2260634,15000,15000,15000.0,60 months,24.85,438.96,E,E3,NaN,NaN,...,60.0,0.0,0.0,17400.0,7067.0,8000.0,6000.0,N,Cash,N
2260635,15000,15000,15000.0,60 months,18.06,381.40,D,D2,Cook,3 years,...,66.7,1.0,0.0,31900.0,16824.0,16300.0,7000.0,N,Cash,N
2260637,23375,23375,23375.0,36 months,21.45,886.07,D,D5,technician,3 years,...,33.3,0.0,0.0,70622.0,44869.0,17600.0,53022.0,N,Cash,N
2260638,30000,30000,30000.0,36 months,21.45,1137.20,D,D5,Cath lab tech,10+ years,...,33.3,0.0,0.0,247780.0,74697.0,14500.0,73836.0,N,Cash,N
2260639,21000,21000,21000.0,36 months,17.09,749.65,D,D1,Supervisor,10+ years,...,25.0,1.0,0.0,275041.0,72844.0,30600.0,67152.0,N,Cash,N
2260640,20700,20700,20700.0,60 months,12.62,466.98,C,C1,Dental Assistant,10+ years,...,50.0,1.0,0.0,82200.0,33323.0,56500.0,16500.0,N,Cash,N
2260642,32400,32400,32375.0,36 months,20.00,1204.11,D,D4,SHIPPING MANGER,3 years,...,75.0,1.0,0.0,42367.0,25360.0,19500.0,17367.0,N,Cash,N
2260644,35000,35000,34725.0,60 months,30.75,1148.55,F,F5,Desktop Support Technician,3 years,...,100.0,0.0,0.0,344978.0,56295.0,16400.0,49578.0,N,Cash,N
2260645,20000,20000,20000.0,36 months,13.59,679.58,C,C2,graphic designer,7 years,...,14.3,1.0,0.0,303325.0,15888.0,15100.0,10225.0,N,Cash,N
2260647,10500,10500,10500.0,36 months,13.59,356.78,C,C2,NaN,NaN,...,66.7,0.0,0.0,39577.0,28685.0,7200.0,28477.0,N,Cash,N
2260648,32000,32000,32000.0,60 months,28.72,1010.30,F,F1,NaN,NaN,...,0.0,0.0,0.0,30800.0,12194.0,23300.0,7500.0,N,Cash,N
2260649,35000,35000,35000.0,36 months,7.97,1096.29,A,A5,Administrative Assistant,3 years,...,0.0,0.0,0.0,666815.0,103095.0,50200.0,96215.0,N,Cash,N
2260651,35000,35000,35000.0,60 months,17.09,871.54,D,D1,Office Manager,< 1 year,...,100.0,0.0,0.0,396635.0,40518.0,15000.0,31500.0,N,Cash,N
2260653,15000,15000,15000.0,36 months,10.91,490.45,B,B4,NaN,NaN,...,33.3,0.0,0.0,51991.0,32926.0,6800.0,38691.0,N,Cash,N
2260654,30000,30000,30000.0,60 months,17.09,747.03,D,D1,Senior Manager,2 years,...,33.3,0.0,0.0,231009.0,196622.0,49300.0,168609.0,N,Cash,N
2260655,18000,18000,18000.0,60 months,30.65,589.57,F,F4,Package Delivery Driver,10+ years,...,50.0,0.0,0.0,338546.0,18113.0,13800.0,7058.0,N,Cash,N
2260657,19000,19000,19000.0,60 months,14.08,442.89,C,C3,NaN,NaN,...,50.0,0.0,0.0,80140.0,44910.0,8000.0,70940.0,N,Cash,N
2260659,3500,3500,3500.0,36 months,10.91,114.44,B,B4,NaN,NaN,...,50.0,0.0,0.0,69600.0,8571.0,4400.0,10000.0,N,Cash,N
2260660,10000,10000,10000.0,36 months,12.62,335.12,C,C1,Administrator,5 years,...,75.0,0.0,0.0,13300.0,11695.0,13300.0,0.0,N,Cash,N
2260661,21000,21000,21000.0,60 months,30.94,691.60,G,G4,NaN,NaN,...,50.0,0.0,0.0,328405.0,68445.0,1300.0,57142.0,N,Cash,N
2260662,30000,30000,30000.0,60 months,30.75,984.47,F,F5,Sales,6 years,...,50.0,0.0,0.0,201286.0,68680.0,16500.0,64086.0,N,Cash,N
2260663,12000,12000,12000.0,60 months,14.08,279.72,C,C3,house keeper,10+ years,...,66.7,0.0,0.0,73948.0,45212.0,6200.0,49448.0,N,Cash,N
2260665,10000,10000,10000.0,36 months,11.99,332.10,B,B5,Teacher,10+ years,...,100.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0,N,Cash,N
2260666,12000,12000,12000.0,60 months,21.45,327.69,D,D5,NaN,NaN,...,0.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0,N,Cash,N
2260667,16550,16550,16550.0,60 months,21.45,451.94,D,D5,BABYSITTER,3 years,...,20.0,0.0,0.0,50700.0,25760.0,19500.0,0.0,N,Cash,N

In [11]:
y=loan_data_cleaned.loan_status
y=y.apply(lambda x: 0 if x=='Current'or x=='In Grace Period' else 1)
y.value_counts()

0    928647
1    290069
Name: loan_status, dtype: int64

In [16]:
loan_data_cleaned=loan_data_cleaned.drop(['emp_title','title','pymnt_plan','zip_code','out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv','total_rec_prncp', 'total_rec_int', 'total_rec_late_fee','recoveries', 'collection_recovery_fee', 'last_pymnt_d','last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d','loan_status','issue_d','earliest_cr_line'],axis=1)

In [17]:
loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1218716 entries, 0 to 2260667
Data columns (total 83 columns):
loan_amnt                     1218716 non-null int64
funded_amnt                   1218716 non-null int64
funded_amnt_inv               1218716 non-null float64
term                          1218716 non-null object
int_rate                      1218716 non-null float64
installment                   1218716 non-null float64
grade                         1218716 non-null object
sub_grade                     1218716 non-null object
emp_length                    1126869 non-null object
home_ownership                1218716 non-null object
annual_inc                    1218712 non-null float64
verification_status           1218716 non-null object
purpose                       1218716 non-null object
addr_state                    1218716 non-null object
dti                           1217255 non-null float64
delinq_2yrs                   1218687 non-null float64
inq_last_6mths                1218687 non-null float64
mths_since_last_delinq        590674 non-null float64
open_acc                      1218687 non-null float64
pub_rec                       1218687 non-null float64
revol_bal                     1218716 non-null int64
revol_util                    1217556 non-null float64
total_acc                     1218687 non-null float64
initial_list_status           1218716 non-null object
collections_12_mths_ex_med    1218621 non-null float64
policy_code                   1218716 non-null int64
application_type              1218716 non-null object
acc_now_delinq                1218687 non-null float64
tot_coll_amt                  1205649 non-null float64
tot_cur_bal                   1205649 non-null float64
open_acc_6m                   1008776 non-null float64
open_act_il                   1008776 non-null float64
open_il_12m                   1008776 non-null float64
open_il_24m                   1008776 non-null float64
mths_since_rcnt_il            974433 non-null float64
total_bal_il                  1008776 non-null float64
il_util                       858689 non-null float64
open_rv_12m                   1008776 non-null float64
open_rv_24m                   1008776 non-null float64
max_bal_bc                    1008776 non-null float64
all_util                      1008600 non-null float64
total_rev_hi_lim              1205649 non-null float64
inq_fi                        1008776 non-null float64
total_cu_tl                   1008776 non-null float64
inq_last_12m                  1008776 non-null float64
acc_open_past_24mths          1209081 non-null float64
avg_cur_bal                   1205594 non-null float64
bc_open_to_buy                1194682 non-null float64
bc_util                       1194130 non-null float64
chargeoff_within_12_mths      1218621 non-null float64
delinq_amnt                   1218687 non-null float64
mo_sin_old_il_acct            1165658 non-null float64
mo_sin_old_rev_tl_op          1205648 non-null float64
mo_sin_rcnt_rev_tl_op         1205648 non-null float64
mo_sin_rcnt_tl                1205649 non-null float64
mort_acc                      1209081 non-null float64
mths_since_recent_bc          1195504 non-null float64
mths_since_recent_inq         1067495 non-null float64
num_accts_ever_120_pd         1205649 non-null float64
num_actv_bc_tl                1205649 non-null float64
num_actv_rev_tl               1205649 non-null float64
num_bc_sats                   1207703 non-null float64
num_bc_tl                     1205649 non-null float64
num_il_tl                     1205649 non-null float64
num_op_rev_tl                 1205649 non-null float64
num_rev_accts                 1205649 non-null float64
num_rev_tl_bal_gt_0           1205649 non-null float64
num_sats                      1207703 non-null float64
num_tl_120dpd_2m              1157187 non-null float64
num_tl_30dpd                  1205649 non-null float64
num_tl_90g_dpd_24m            1205649 non-null float64
num_tl_op_past_12m            1205649 non-null float64
pct_tl_nvr_dlq                1205626 non-null float64
percent_bc_gt_75              1194570 non-null float64
pub_rec_bankruptcies          1217930 non-null float64
tax_liens                     1218649 non-null float64
tot_hi_cred_lim               1205649 non-null float64
total_bal_ex_mort             1209081 non-null float64
total_bc_limit                1209081 non-null float64
total_il_high_credit_limit    1205649 non-null float64
hardship_flag                 1218716 non-null object
disbursement_method           1218716 non-null object
debt_settlement_flag          1218716 non-null object
dtypes: float64(66), int64(4), object(13)
memory usage: 781.0+ MB

In [22]:
loan_data[loan_data.hardship_flag=='N'].loan_status.value_counts()

Fully Paid                                             1041952
Current                                                 919685
Charged Off                                             261654
Late (31-120 days)                                       21118
In Grace Period                                           8920
Late (16-30 days)                                         3674
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     31
Name: loan_status, dtype: int64

In [6]:
#loan_data_cleaned.last_pymnt_d.value_counts()

In [7]:
v1=loan_data_cleaned
v1=v1.drop(['emp_title','title','pymnt_plan','zip_code','out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv','total_rec_prncp', 'total_rec_int', 'total_rec_late_fee','recoveries', 'collection_recovery_fee', 'last_pymnt_d','last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d','loan_status','issue_d','earliest_cr_line'],axis=1)
#ready_for_split.issue_d=pd.to_datetime(ready_for_split.issue_d,format='%b-%y')
#columns that need to be converted to datetiem: issuw_d,last_pymnt_d, next_pymnt_d, last_credit_pull_d
v1.loan_status.value_counts()
v2=v1[v1.loan_status!='Fully Paid']
v2.loan_status.value_counts()

Current                                                919695
Charged Off                                            261655
Late (31-120 days)                                      21897
In Grace Period                                          8952
Late (16-30 days)                                        3737
Does not meet the credit policy. Status:Fully Paid       1988
Does not meet the credit policy. Status:Charged Off       761
Default                                                    31
Name: loan_status, dtype: int64

In [8]:
v2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1218716 entries, 0 to 2260667
Data columns (total 86 columns):
loan_amnt                     1218716 non-null int64
funded_amnt                   1218716 non-null int64
funded_amnt_inv               1218716 non-null float64
term                          1218716 non-null object
int_rate                      1218716 non-null float64
installment                   1218716 non-null float64
grade                         1218716 non-null object
sub_grade                     1218716 non-null object
emp_length                    1126869 non-null object
home_ownership                1218716 non-null object
annual_inc                    1218712 non-null float64
verification_status           1218716 non-null object
issue_d                       1218716 non-null object
loan_status                   1218716 non-null object
purpose                       1218716 non-null object
addr_state                    1218716 non-null object
dti                           1217255 non-null float64
delinq_2yrs                   1218687 non-null float64
earliest_cr_line              1218687 non-null object
inq_last_6mths                1218687 non-null float64
mths_since_last_delinq        590674 non-null float64
open_acc                      1218687 non-null float64
pub_rec                       1218687 non-null float64
revol_bal                     1218716 non-null int64
revol_util                    1217556 non-null float64
total_acc                     1218687 non-null float64
initial_list_status           1218716 non-null object
collections_12_mths_ex_med    1218621 non-null float64
policy_code                   1218716 non-null int64
application_type              1218716 non-null object
acc_now_delinq                1218687 non-null float64
tot_coll_amt                  1205649 non-null float64
tot_cur_bal                   1205649 non-null float64
open_acc_6m                   1008776 non-null float64
open_act_il                   1008776 non-null float64
open_il_12m                   1008776 non-null float64
open_il_24m                   1008776 non-null float64
mths_since_rcnt_il            974433 non-null float64
total_bal_il                  1008776 non-null float64
il_util                       858689 non-null float64
open_rv_12m                   1008776 non-null float64
open_rv_24m                   1008776 non-null float64
max_bal_bc                    1008776 non-null float64
all_util                      1008600 non-null float64
total_rev_hi_lim              1205649 non-null float64
inq_fi                        1008776 non-null float64
total_cu_tl                   1008776 non-null float64
inq_last_12m                  1008776 non-null float64
acc_open_past_24mths          1209081 non-null float64
avg_cur_bal                   1205594 non-null float64
bc_open_to_buy                1194682 non-null float64
bc_util                       1194130 non-null float64
chargeoff_within_12_mths      1218621 non-null float64
delinq_amnt                   1218687 non-null float64
mo_sin_old_il_acct            1165658 non-null float64
mo_sin_old_rev_tl_op          1205648 non-null float64
mo_sin_rcnt_rev_tl_op         1205648 non-null float64
mo_sin_rcnt_tl                1205649 non-null float64
mort_acc                      1209081 non-null float64
mths_since_recent_bc          1195504 non-null float64
mths_since_recent_inq         1067495 non-null float64
num_accts_ever_120_pd         1205649 non-null float64
num_actv_bc_tl                1205649 non-null float64
num_actv_rev_tl               1205649 non-null float64
num_bc_sats                   1207703 non-null float64
num_bc_tl                     1205649 non-null float64
num_il_tl                     1205649 non-null float64
num_op_rev_tl                 1205649 non-null float64
num_rev_accts                 1205649 non-null float64
num_rev_tl_bal_gt_0           1205649 non-null float64
num_sats                      1207703 non-null float64
num_tl_120dpd_2m              1157187 non-null float64
num_tl_30dpd                  1205649 non-null float64
num_tl_90g_dpd_24m            1205649 non-null float64
num_tl_op_past_12m            1205649 non-null float64
pct_tl_nvr_dlq                1205626 non-null float64
percent_bc_gt_75              1194570 non-null float64
pub_rec_bankruptcies          1217930 non-null float64
tax_liens                     1218649 non-null float64
tot_hi_cred_lim               1205649 non-null float64
total_bal_ex_mort             1209081 non-null float64
total_bc_limit                1209081 non-null float64
total_il_high_credit_limit    1205649 non-null float64
hardship_flag                 1218716 non-null object
disbursement_method           1218716 non-null object
debt_settlement_flag          1218716 non-null object
dtypes: float64(66), int64(4), object(16)
memory usage: 808.9+ MB

In [26]:
X=pd.get_dummies(loan_data_cleaned,drop_first=True)

In [27]:
X_forest=X.fillna(X.median())

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X_train,X_test,y_train,y_test=train_test_split(X_forest,y,test_size=.25,random_state=42)
rf=RandomForestClassifier(n_estimators=50, random_state=42)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.8703159718917287

In [29]:
rf.score(X_train,y_train)

0.9995897321443223

In [48]:
s1=pd.DataFrame(X_forest.columns.values)
s1.columns=['column_name']
s1.loc[:,'column_importance']=rf.feature_importances_
s1

                       column_name  column_importance
0                        loan_amnt           0.011927
1                      funded_amnt           0.012509
2                  funded_amnt_inv           0.013048
3                         int_rate           0.029775
4                      installment           0.016502
5                       annual_inc           0.012367
6                              dti           0.013733
7                      delinq_2yrs           0.002715
8                   inq_last_6mths           0.007318
9           mths_since_last_delinq           0.009084
10                        open_acc           0.007720
11                         pub_rec           0.002689
12                       revol_bal           0.012845
13                      revol_util           0.013190
14                       total_acc           0.010194
15      collections_12_mths_ex_med           0.000731
16                     policy_code           0.000000
17                  acc_now_delinq           0.000198
18                    tot_coll_amt           0.004217
19                     tot_cur_bal           0.013328
20                     open_acc_6m           0.017244
21                     open_act_il           0.013672
22                     open_il_12m           0.012322
23                     open_il_24m           0.016854
24              mths_since_rcnt_il           0.046608
25                    total_bal_il           0.041114
26                         il_util           0.025318
27                     open_rv_12m           0.014628
28                     open_rv_24m           0.018592
29                      max_bal_bc           0.038146
..                             ...                ...
166                  addr_state_MT           0.000159
167                  addr_state_NC           0.000786
168                  addr_state_ND           0.000143
169                  addr_state_NE           0.000280
170                  addr_state_NH           0.000248
171                  addr_state_NJ           0.000899
172                  addr_state_NM           0.000313
173                  addr_state_NV           0.000615
174                  addr_state_NY           0.001331
175                  addr_state_OH           0.000765
176                  addr_state_OK           0.000472
177                  addr_state_OR           0.000377
178                  addr_state_PA           0.000827
179                  addr_state_RI           0.000240
180                  addr_state_SC           0.000421
181                  addr_state_SD           0.000158
182                  addr_state_TN           0.000577
183                  addr_state_TX           0.001289
184                  addr_state_UT           0.000318
185                  addr_state_VA           0.000724
186                  addr_state_VT           0.000119
187                  addr_state_WA           0.000541
188                  addr_state_WI           0.000499
189                  addr_state_WV           0.000125
190                  addr_state_WY           0.000137
191          initial_list_status_w           0.018917
192     application_type_Joint App           0.001742
193                hardship_flag_Y           0.001181
194  disbursement_method_DirectPay           0.002060
195         debt_settlement_flag_Y           0.049373

[196 rows x 2 columns]

In [ ]:
RandomForestClassifier()

In [49]:
params={'n_estimators':[10,50,100,150,200],'max_depth':[10,20,30,40,50],'max_features':[.1,.2,.4,.6,.9]}

In [ ]:
from sklearn.model_selection import GridSearchCV
gcv=GridSearchCV(rf,params,cv=5)
gcv.fit(X_train,y_train)